version: '3'
services:

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: semaphore
      MYSQL_USER: semaphore
      MYSQL_PASSWORD: semaphore
    #ports:
      #- "3306:3306"
#    networks:
#      frontend:
#        ipv4_address: 172.20.0.4

  semaphore:
    image: qcdis/docker_ansible_semaphore
    environment:
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: semaphore
      SEMAPHORE_DB_HOST: mysql
      SEMAPHORE_DB_PORT: 3306
      SEMAPHORE_DB: semaphore
      SEMAPHORE_PLAYBOOK_PATH: /etc/semaphore
      SEMAPHORE_ADMIN_PASSWORD: password
      SEMAPHORE_ADMIN_NAME: "Developer"
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_WEB_ROOT: http://0.0.0.0:3000
    ports:
      - "3000:3000"
    depends_on:
      - mysql

  sure-tosca:
    image: qcdis/sure-tosca
    ports:
      - "8081:8081"


  compute:
    image: ubuntu:18.04
    volumes:
      - "./run_test_nodes.sh:/tmp/run_test_nodes.sh"
      - "/var/run/docker.sock:/var/ru/docker.sock"
    command: "/tmp/run_test_nodes.sh"

  compute_1:
    image: ubuntu:18.04
    volumes:
      - "./run_test_nodes.sh:/tmp/run_test_nodes.sh"
      - "/var/run/docker.sock:/var/ru/docker.sock"
    command: "/tmp/run_test_nodes.sh"







